version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    restart: unless-stopped
    networks:
      - phpmyadmin
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=testlyes.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=bd21a5d7-aa7b-426f-a271-4f4850ff841f
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - phpmyadmin

  awslaravel:
    build:
      context: ./awsLaravel
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "82:81"
    volumes:
      - ./awsLaravel/laravel:/var/www/html

  db_dev:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - db_dev_data:/var/lib/mysql
    networks:
      - db_network

  db_test:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - db_test_data:/var/lib/mysql
    networks:
      - db_network

  db_prod:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - db_prod_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
  
    image: lscr.io/linuxserver/phpmyadmin:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com #optional    volumes:

    networks:
      - db_network
      - phpmyadmin
      
networks:
  db_network:
  phpmyadmin:
volumes:
  db_dev_data:
  db_test_data:
  db_prod_data: